### ISSUE TITLE
Fingerprint Bug?

### ISSUE THREAD

**Issue by ghost** [omnirom/android_device_oneplus_oneplus6t#2]
Finger print doesn't register for me. 
Icon lights up but no progress in FP registration

[ADB Logcat](https://cryptpad.fr/code/#/2/code/view/zZpJ4UYr57ikwdD5y49j+fdpdnNZRiSXa+I2Bvrrx1g/)

**Comment by darkobas** [comment]
Probably custom/wrong kernel
